# Generated by Django 5.0.6 on 2024-06-19 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='date_attempted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
