# Generated by Django 4.2.13 on 2024-06-19 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='date_attempted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
