# Generated by Django 4.2.13 on 2024-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_codesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_experience', models.IntegerField()),
                ('technical_issues', models.TextField()),
                ('overall_satisfaction', models.IntegerField()),
                ('challenges_faced', models.TextField()),
                ('assessment_quality', models.IntegerField()),
                ('changes_request', models.TextField()),
            ],
        ),
    ]
